import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DraftsProvider from "./provider/DraftsProvider";
import Header from "./components/global/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GitHub User Markdown Publisher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DraftsProvider>
          <Header />
          <main className='py-4 sm:py-8'>
            {children}
          </main>
        </DraftsProvider>
      </body>
    </html>
  );
}
